import dotenv from "dotenv";
import OpenAI from 'openai';

dotenv.config();

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const modelName = 'gpt-5-mini';
const footer = "--- Generated by \n\n" + modelName + "\n\n---\n\nemailwithaimodels.com\n\n---\n\n";

export async function processEmail({ from, to, subject, text }) {

  const response = await client.responses.create({
    model: modelName,
    instructions: 'You are responding to a professional email.',
    input: (text || "").trim(),
  });
  const responseText = response.output_text;

  return responseText + "\n\n " + footer;
}
